import { generate } from "./client";
import type { StateMachine, GeneratedCode, GenerationOptions } from "./types";

export async function generateCode(
  machine: StateMachine,
  options: GenerationOptions,
  frameUrls?: string[],
): Promise<GeneratedCode> {
  const stateDescriptions = machine.states
    .map(
      (s) =>
        `  - "${s.name}" (${s.type}): ${s.description} [${s.startTime}s-${s.endTime}s]`,
    )
    .join("\n");

  const transitionDescriptions = machine.transitions
    .map(
      (t) =>
        `  - ${t.triggerType}: "${t.description}" (${t.durationMs}ms, ${t.easing})`,
    )
    .join("\n");

  const prompt = `You are a senior React developer. Generate a COMPLETE, WORKING React application based on this state machine extracted from a UI recording.

## States (${machine.states.length}):
${stateDescriptions}

## Transitions (${machine.transitions.length}):
${transitionDescriptions}

${
  frameUrls && frameUrls.length > 0
    ? `
## Reference Screenshots
Here are actual screenshots from the recording. Use them as visual reference:
${frameUrls
  .slice(0, 5)
  .map((url, i) => `Screenshot ${i + 1}: ${url}`)
  .join("\n")}
`
    : ""
}

## Requirements:
- Use React 19 + TypeScript + Tailwind CSS
${options.componentLib === "shadcn" ? "- Use shadcn/ui components where appropriate" : ""}
- Use ${options.stateManagement} for state management
- Include ALL these states: loading, error, empty, and every detected state
- Add optimistic updates for any list operations
- Add proper TypeScript types
- Add accessible aria attributes
- Generate a main App component and any needed sub-components
- Use lucide-react for icons
- Include proper form validation if there are forms
- Style it like a modern SaaS application (dark theme preferred)

Output a JSON object with a "files" array:
{
  "files": [
    { "filename": "App.tsx", "language": "tsx", "content": "..." },
    { "filename": "components/Modal.tsx", "language": "tsx", "content": "..." },
    ...any other files needed
  ]
}

Return ONLY the JSON object. No explanations.`;

  try {
    const result = await generate(prompt);
    const parsed = JSON.parse(extractJSONBlock(result));
    return {
      files: parsed.files || [
        {
          filename: "App.tsx",
          language: "tsx",
          content: `// Generated by PixelForge\nexport default function App() { return <div>Generated app</div> }`,
        },
      ],
    };
  } catch {
    return { files: [fallbackComponent(machine)] };
  }
}

function fallbackComponent(machine: StateMachine): {
  filename: string;
  language: string;
  content: string;
} {
  return {
    filename: "App.tsx",
    language: "tsx",
    content: `import { useState } from 'react'\n\nexport default function App() {\n  const states = ${JSON.stringify(
      machine.states.map((s) => s.name),
      null,
      2,
    )}\n  return <div className="p-8 dark:bg-gray-900 min-h-screen text-white">\n    <h1 className="text-2xl font-bold">Generated App</h1>\n    <p>States: {states.join(', ')}</p>\n  </div>\n}`,
  };
}

function extractJSONBlock(text: string): string {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}") + 1;
  if (start >= 0 && end > start) return text.slice(start, end);
  return "{}";
}
